/**
 * ExportButton - Export requirements as Markdown
 */

import React from 'react';
import { useProjectStore } from '../../store/useProjectStore';
import { Download } from 'lucide-react';

export const ExportButton: React.FC = () => {
  const { currentProject } = useProjectStore();

  const exportAsMarkdown = () => {
    if (!currentProject || !currentProject.requirements) {
      alert('No requirements to export');
      return;
    }

    // Create markdown content with metadata
    const content = `${currentProject.requirements}

---
*Generated by HTML Prototype Builder - BA Mode*  
*Project: ${currentProject.name}*  
*Date: ${new Date().toLocaleDateString()}*
`;

    // Create blob and download
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${currentProject.name.replace(/\s+/g, '-').toLowerCase()}-requirements.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    console.log('✅ Requirements exported as Markdown');
  };

  return (
    <button
      onClick={exportAsMarkdown}
      className="flex items-center gap-2 px-3 py-1 text-sm border border-gray-300 rounded hover:bg-gray-50"
      title="Export as Markdown"
    >
      <Download size={16} />
      Export MD
    </button>
  );
};
